# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Agent multiplexer that lives in your terminal
brew "herdr"
# Simple terminal UI for git commands
brew "lazygit"
# YAML Parser
brew "libyaml"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Language Server for the Lua language
brew "lua-language-server"
# Package manager for the Lua programming language
brew "luarocks"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Fast, disk space efficient package manager
brew "pnpm"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Opinionated Lua code formatter
brew "stylua"
# Terminal multiplexer
brew "tmux"
# Parser generator tool
brew "tree-sitter-cli"
# Internet file retriever
brew "wget"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# A simple terminal UI for docker, written in Go
brew "lazydocker"
cask "font-jetbrains-mono"
