-- lua/ak/plugins/surround.lua
--
-- Add, change, and delete surrounding pairs — quotes, brackets, HTML/JSX tags,
-- Ruby do...end blocks.
--
-- Defaults are good, so setup() is called empty. What follows is a reference
-- for the keymaps it installs, because they're the kind you forget if you
-- don't use them for a week.
--
--   ys{motion}{char}   add surround        ysiw"   foo   -> "foo"
--   yss{char}          surround whole line
--   yS{motion}{char}   add on its own lines
--   ds{char}           delete surround     ds"     "foo" -> foo
--   cs{old}{new}       change surround     cs"'    "foo" -> 'foo'
--   S{char}            surround selection  (visual mode)
--   <C-g>s{char}       surround in insert mode
--
-- Useful chars: " ' ` ( ) [ ] { } < > t (HTML/JSX tag) f (function call)
--
-- Worth knowing for your two stacks specifically:
--
--   TSX   cst  changes the surrounding JSX tag and its closing partner —
--              <div>x</div> -> <span>x</span> with one command. Note this
--              overlaps with vtsls' linkedEditingRange (enabled in lsp.lua),
--              which auto-renames the closing tag as you type the opening one.
--              They're complementary: linked editing is for typing, cst is for
--              a deliberate motion.
--
--   Ruby  ysiwf then typing a name wraps a word in a function call.
--         cs"'  is constant in Rails work — swapping between "..." and '...'
--         to satisfy rubocop's Style/StringLiterals.
--
-- No keymaps are defined here: the plugin installs the ones above itself, and
-- none of them collide with anything in keymaps.lua (checked — our visual-mode
-- maps are J, K, <, >, and <leader>P).
require('nvim-surround').setup({})
